<a href="https://colab.research.google.com/github/roybibek/Numpy-tutorial/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Note: This nb is meant to be semi-self introductory. Some parts that are vague have to be experimented and found out by the user. Feel free to use this notebook as you wish too.

This provides a brief introduction to Numpy. Futher exploration is up to you

Import Numpy

In [0]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

Convert List to Array

In [3]:
np.array(my_list)

array([1, 2, 3])

Creating multi dimensional vectors

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Converting my_matrix to Numpy Array

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Arange is used to generate numbers between the range specified Mind the single r

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Another varient with the step size mentioned

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

Zeroes is used to create an array with 0 as values

In [8]:
np.zeros(3)

array([0., 0., 0.])

Multi-dimensional

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])


np.ones() is used to create an array with all values set to 1.

In [11]:
np.ones(3)

array([1., 1., 1.])


Multi Dimensional Example

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])


np.linspace() is used to create a linearly spaced array

In [13]:

np.linspace(0,10,3)

array([ 0.,  5., 10.])

Multi Dimensional example

In [14]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [15]:

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

np.random.rand() is used to create random numbered arrays (range from 0-1)

In [16]:
np.random.rand(2)

array([0.87780906, 0.32238304])


Multi Dimensional example

In [17]:
np.random.rand(5,5)

array([[0.14690633, 0.23272424, 0.95537602, 0.95458371, 0.29246378],
       [0.38880961, 0.27459999, 0.41465691, 0.30325559, 0.95118683],
       [0.15088011, 0.80640762, 0.2644347 , 0.82446816, 0.55057237],
       [0.77683703, 0.2156461 , 0.49424973, 0.30699345, 0.98388777],
       [0.53604264, 0.75308087, 0.525496  , 0.59377535, 0.28648924]])


np.random.randn() Press Shift+tab to find the difference between rand() and randn()

In [18]:

np.random.randn(2)

array([0.30305052, 0.29846438])

In [19]:

np.random.randn(5,5)

array([[ 0.88504186,  0.75099188, -0.38229507, -1.92532617, -0.92492412],
       [-0.99233649, -0.1053997 , -0.12097047,  1.11528918, -0.50074854],
       [-1.0994727 ,  2.24223409, -1.04599239,  0.26344743,  1.22381739],
       [ 0.44779091, -0.67870672, -0.97914697, -0.63905546,  0.44366926],
       [ 0.50935147, -0.93839973, -1.82558503, -0.73946812, -1.04781116]])


randint() returns a random integer from the range specified

In [20]:
np.random.randint(1,100)

96


To return more than one integeres

In [21]:
np.random.randint(1,100,10)

array([55, 33, 46, 64, 64, 80, 43, 97, 48, 94])

In [0]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr

array([43, 26, 13, 34, 23, 26,  7, 38, 45, 32])

reshape() is used to reshape() the array into the desired shape

In [27]:

arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
ranarr

array([43, 26, 13, 34, 23, 26,  7, 38, 45, 32])

In [29]:
ranarr.max()

45

max() and argmax() return the maximum value and it's index

In [30]:

ranarr.argmax()

8

max() and argmax() return the maximum value and it's index

In [31]:
ranarr.argmax()

8

min() is used to return the minimum value

In [32]:
ranarr.min()

7

In [33]:

ranarr.argmin()

6

.shape is an attribute of Numpy Objects that is used to display the shape of the object.

In [34]:
# Vector
arr.shape

(25,)

In [35]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [36]:
arr.reshape(1,25).shape

(1, 25)

In [37]:

arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [38]:
arr.reshape(25,1).shape

(25, 1)


You can check the type by checking the .dtype attribute

In [39]:

arr.dtype

dtype('int64')

In [0]:
#Creating sample array
arr = np.arange(0,11)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Accessing index values

In [42]:
#Get a value at an index
arr[8]

8

Slicing. starting pos:Finalpos-1

In [43]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [44]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [45]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [46]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [48]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [49]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [50]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [51]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [52]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [53]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [54]:
# Getting individual element value
arr_2d[1,0]

20

In [55]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [56]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [57]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [0]:
#Set up matrix
arr2d = np.zeros((10,10))

In [0]:
#Length of array
arr_length = arr2d.shape[1]

In [60]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [61]:

arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [62]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [63]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:

arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [0]:
bool_arr = arr>4

In [66]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [67]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [68]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr = np.arange(0,10)

In [71]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [72]:

arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [73]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [74]:
# Also warning, but not an error instead infinity
1/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [75]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [76]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [77]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [78]:
np.max(arr) #same as arr.max()

9

In [79]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [80]:
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])